MY_MVCProjeKampi/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using FluentValidation.Results;
using BusinessLayer.ValidationRules.FluentValidation;

namespace MY_MVCProjeKampi.Controllers
{
    public class WriterPanelController : Controller
    {
        // GET: WriterPanel
        HeadingManager headingManager = new HeadingManager(new EfHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        WriterManager writerManager = new WriterManager(new EfWriterDal());
        WriterValidator writerValidation = new WriterValidator();
        Context c = new Context();
        [HttpGet]
        public ActionResult WriterProfile(int id=0)
        {
            string p = (string)Session["WriterMail"];
            id = c.Writers.Where(x => x.WriterMail == p).Select(x => x.WriterId).FirstOrDefault();
            var writerValues = writerManager.GetById(id);
            return View(writerValues);
        }


        [HttpPost]
        public ActionResult WriterProfile(Writer entity)
        {
            ValidationResult result = writerValidation.Validate(entity);
            if (result.IsValid)
            {
                writerManager.Update(entity);
                return RedirectToAction("AllHeading");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult MyHeading(string p)
        {
            
            p = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == p).Select(x => x.WriterId).FirstOrDefault();
            var values = headingManager.GetAllByWriter(writerIdInfo);
            return View(values);
        }

        [HttpGet]
        public ActionResult NewHeading()
        {

            List<SelectListItem> values = (from x in categoryManager.GetAll()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryId.ToString()
                                           }).ToList();
            ViewBag.vlc = values;
            return View();
        }
        [HttpPost]
        public ActionResult NewHeading(Heading entity)
        {
            string currentWriterMail = (string)Session["WriterMail"];
            var writerIdInfo = c.Writers.Where(x => x.WriterMail == currentWriterMail).Select(x => x.WriterId).FirstOrDefault();
            entity.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            entity.WriterId = writerIdInfo;
            entity.HeadingStatus = true;
            headingManager.Add(entity);
            return RedirectToAction("MyHeading");
        }

        [HttpGet]
        public ActionResult UpdateHeading(int id)
        {
           
            List<SelectListItem> valueCategory = (from x in categoryManager.GetAll()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();

            ViewBag.vlc = valueCategory;
            var headingValue = headingManager.GetById(id);
            return View(headingValue);
        }

        [HttpPost]
        public ActionResult UpdateHeading(Heading entity)
        {
            headingManager.Update(entity);
            return RedirectToAction("MyHeading");
        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = headingManager.GetById(id);
            headingValue.HeadingStatus = false;
            headingManager.Delete(headingValue);
            return RedirectToAction("MyHeading");
        }

        public ActionResult AllHeading(int page=1)
        {
            var headings = headingManager.GetAll().ToPagedList(page, 4);
            return View(headings);
        }
    }
}

MY_MVCProjeKampi/Views/WriterPanel/AllHeading.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Heading>
@{
    ViewBag.Title = "AllHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>AllHeading</h2>

@{string color = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Projects</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Sport")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Film")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-secondary";
                            }
                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Default/Headings/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanelContent/AddContent/@item.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Bu Başlığa Yaz
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
@Html.PagedListPager((IPagedList)Model, page => Url.Action("AllHeading", new { page }), new PagedListRenderOptions
{
LiElementClasses = new List<string>
{ "page-link"}
})

MY_MVCProjeKampi/Views/WriterPanel/MyHeading.cshtml
@using EntityLayer.Concrete
@model List<Heading>

@{
    ViewBag.Title = "MyHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
@{ string color = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Projects</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Sport")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Film")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-secondary";
                            }
                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanel/UpdateHeading/@item.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/WriterPanel/DeleteHeading/@item.HeadingId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
<a href="/WriterPanel/NewHeading/" class="btn btn-primary">Yeni Başlık Girişi</a>

MY_MVCProjeKampi/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}



@using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Oluştur</button>
    </div>
}

MY_MVCProjeKampi/Views/WriterPanel/UpdateHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "UpdateHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Panel Update</h2>

@using (Html.BeginForm("UpdateHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HeadingId)
        @Html.HiddenFor(x => x.HeadingDate)
        @Html.HiddenFor(x => x.WriterId)
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategorisi")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

MY_MVCProjeKampi/Views/WriterPanel/WriterProfile.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Profilinizi Düzenleyin</h2>
@using (Html.BeginForm("WriterProfile", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.WriterId, new { @class = "form-control" })
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName)
        <br />
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.WriterSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterSurname)
        <br />
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail)
        <br />
        @Html.Label("Yazar Şifresi")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword)
        <br />
        @Html.Label("Yazar Görsel Linki")
        @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage)
        <br />
        @Html.Label("Yazar Ünvanı")
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterTitle)
        <br />
        @Html.Label("Yazar Hakkında")
        @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout)
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}